http_path = "/"
css_dir = "../css"
sass_dir = "./"
images_dir = "../img"
javascripts_dir = "../js"
environment = :development
relative_assets = true
output_style = :expanded
# line_comments = false
preferred_syntax = :scss
